# Generated by Django 3.1.5 on 2021-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210121_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='outcome',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
