# Generated by Django 3.1.5 on 2021-01-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210122_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='noun',
            field=models.CharField(default='', max_length=255),
        ),
    ]
