# Generated by Django 3.1.5 on 2021-02-01 15:30

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210201_1115'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='habit',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_habit',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_record'),
        ),
    ]
