# Generated by Django 3.1.5 on 2021-02-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210201_1530'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='habit',
            managers=[
            ],
        ),
    ]
