# Generated by Django 3.1.5 on 2021-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210201_1608'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_record',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit'),
        ),
    ]
