# Generated by Django 3.1.5 on 2021-02-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210201_1843'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_habit',
        ),
    ]
