# Generated by Django 3.1.5 on 2021-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210201_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
